steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}',
      '-t', '${_IMAGE_NAME}',
      '.'
    ]
images:
  - '${_IMAGE_NAME}'
